name: OCaml CI

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.0.0
    
    - name: Install OPAM dependencies
      run: |
        opam init -y
        eval $(opam env)
        opam install -y ocamllex llvm menhir
    
    - name: Build with Dune
      run: |
        dune build @install
